### ISSUE TITLE
Getting error: Developer console is not set up correctly.

### ISSUE THREAD

**Issue by shreyas29** [jabirdev/OneTap#1]
I am getting this error but not sure what I am missing. I also followed your YouTube video.

![WhatsApp Image 2022-02-24 at 12 17 18 AM](https://user-images.githubusercontent.com/16454030/155386886-accd1de0-8677-4c56-8dba-4c0f103e63df.jpeg)

Can you please help?

**Comment by shreyas29** [comment]
I got it. I was using android client id instead of web client id.

**Comment by Luizvnx** [comment]
can u help me? i'm having that same problem

**Comment by shreyas29** [comment]
I have already mentioned the solution. Do you still get the same issue?
